export { IPC_CHANNELS, EQUIPMENT_STATUS, EQUIPMENT_STATUS_CONFIG, CONDITION_GRADES,
  REPAIR_STATUS, REPAIR_STATUS_CONFIG, SEVERITY_CONFIG, PARTS_CATEGORY_CONFIG,
  CATEGORY_PREFIXES, EQUIPMENT_HIERARCHY } from '../../shared/constants';

export const TOAST_DURATION_MS = 4000;
export const SIDEBAR_WIDTH = 260;
export const SIDEBAR_COLLAPSED_WIDTH = 64;
